name: e2e
on: 
  workflow_dispatch:
    inputs:
      deployed_url:
        description: 'deployed url'
        required: true
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Sleeping
        run: |
          sleep 2s
